spring.application.name=bank
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.main.web-application-type=servlet
server.port=8081
spring.h2.console.path=/h2-console
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=nava
spring.datasource.password=nava
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.security.frameoptions.disable=true
spring.datasource.url=jdbc:h2:file:./data/bankdb;DB_CLOSE_DELAY=-1
spring.jpa.hibernate.ddl-auto=update
springdoc.override-with-generic-response=false
logging.level.org.springframework.security=DEBUG
spring.data.rest.detection-strategy=annotated
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
auto.create.topics.enable=true