spring.application.name=bank
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.main.web-application-type=servlet
server.port=8080
spring.h2.console.path=/h2-console
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=nava
spring.datasource.password=nava
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.security.frameoptions.disable=true
spring.datasource.url=jdbc:h2:file:./data/bankdb;DB_CLOSE_DELAY=-1

